### ISSUE TITLE
Your code of conduct sucks

### ISSUE THREAD

**Issue by somebodythatiusedtoblow** [unified-moderation-network/salamander#50]
For a "white guy in tech" that claims to be an "ally" your project code of conduct sucks. "Good ideas can come from anywhere." and "Participants should be tolerant of others." are the two most priveleged statements I've seen in a project. Adopt the contributor covenant if you want to have a code of conduct that means something. Or just go back to being pissed off at people and "just blowing situations up". you're good at that.

**Comment by mikeshardmind** [comment]
I'm going to choose to respond to the specific issue you have taken with the code of conduct and not any personal jabs that were included.

If you have any grievances with members of this project, please do not air them here. If instead you would like to try and convince me to switch the code of conduct, I'm at least open to a discussion on why I should, but I'd like to address the specific things that have been said about the current one first.


### "Good ideas can come from anywhere." and "Participants should be tolerant of others." are the two most priveleged statements I've seen in a project. 

These are both statements that I wrote. So for the sake of having a constructive discussion, I'm fine to read everything here in the most charitable light regarding bringing privilege into it. 

I could have more accurately written something to the effect of:

> While good ideas can come from anywhere in theory, in practice much of the knowledge those ideas are built upon isn't accessible to everyone in an equal fashion.

I don't disagree that there are circumstances and environments which provide more opportunities to learn about things that could spark ideas built on existing concepts or that certain environments grant those fortunate enough to be in those enviornments more time to have the luxury to spend dreaming ideas.

With all of that said, at its core the statement was to the benefit of not dismissing ideas no matter who came up with them. While these qualifiers are good to be aware of and they should be things that are said and worked on, saying them in this code of conduct would not help improve those inequalities.

### Participants should be tolerant of others.

The very next line is 

> Personal views and beliefs are not to be used to excuse harassment or any other behavior which is harmful to others collaborating.

And I'm also a firm believer that valuing tolerance mandates being intolerant of intolerance. I will not personally allow tolerance to be used as a shield for bullies and those with power to hide behind in situations where I have the ability to act.

### Adopt the contributor covenant if you want to have a code of conduct that means something. 

I want the guidelines to fit in a single screen and be easily understood. I feel like I may have missed the mark on that given the issues you have with the wording.

While I do not like the way in which this issue was brought up, I am open to changing the wording to help make this more welcoming and clear.

However, I do not like the contributor covenenant. I feel that it is extremely broad and raises questions about where it actually applies that makes it my job as someone moderating this space to also moderate other spaces which I have no moderation capacity in.

If you have specific suggestions for improving the wording I have used here or reasons why I should consider the contributor covenant despite my issue with it, I am happy to consider them.

For now, I'm closing this issue, but I will remain engaged with any further responses if the discussion can remain productive.
